name: 'Bridgecrew Github Action'
author: 'Bridgecrew.io'
description: 'Find and fix security and compliance issues in infrastructure code using Bridgecrew Action'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
    required: false
  check:
    description: 'Run scan only on a specific check identifier (comma separated)'
    required: false
  skip_check:
    description: 'Run scan on all checks but a specific check identifier (comma separated)'
    required: false
  quiet:
    description: 'display only failed checks'
    required: false
  api-key:
    description: 'Environment variable name of the Bridgecrew API key from Bridgecrew app'
    required: false
  soft-fail:
    description: 'Runs checks but suppresses error code'
    required: false
  external-checks-dir:
    description: 'Directory for custom checks to be loaded'
    required: false
  output_format:
    description: 'Output Format (cli, cli+sarif, json, junitxml)'
    required: false
    default: 'sarif'


branding:
  icon: 'shield'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.check }}
    - ${{ inputs.skip_check }}
    - ${{ inputs.quiet }}
    - ${{ inputs.soft-fail }}
    - ${{ inputs.external-checks-dir }}
    - ${{ inputs.output_format }}
  env:
    API_KEY_VARIABLE: ${{ inputs.api-key }}
