name: 'Bridgecrew Github Action'
author: 'Bridgecrew.io'
description: 'Run Bridgecrew against infrastructure code, as a pre-packaged Github Action.'
inputs:
  api-key-variable:
    description: 'Environment variable name of the Bridgecrew API key from Bridgecrew app'
    required: false

  directory:
    description: 'Directory with infrastructure code to scan'
    default: 'none'
    required: false

  file:
    description: 'IaC file to scan'
    default: 'none'
    required: false

  soft-fail:
    description: 'Runs checks but suppresses error code'
    default: 'false'
    required: false

  output:
    description: 'Report output format'
    default: 'cli'
    required: false

branding:
  icon: 'shield'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_KEY_VARIABLE: ${{ inputs.api-key-variable }}
    DIRECTORY: ${{ inputs.directory }}
    FILE: ${{ inputs.file }}
    SOFT_FAIL: ${{ inputs.soft-fail }}
    OUTPUT: ${{ inputs.output }}