name: build
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update-bridgecrew:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: update release
        run: |
          # update bridgecrew version
          bridgecrew_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo "bridgecrew==$bridgecrew_version" > 'requirements.txt'
          echo "version = '$bridgecrew_version'"

          # create a release
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch --tags
          git commit -am "update bridgecrew version to '$bridgecrew_version'"
          git push
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
